services:
  db:
    image: postgres:13
    container_name: postgres-vimnotes
    environment:
      #Set this to what you want
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vimnotes
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
  client:
    env_file: ".env"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5173:5173
  api:
    depends_on:
      - db
    env_file: ".env"
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - ${EXPRESS_PORT}:5001
volumes:
  pgdata:
